apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: devops-api
data:
  NODE_ENV: "production"
  PORT: "3000"
  PGHOST: "postgres-svc"
  PGPORT: "5432"
  PGDATABASE: "app"
  PGUSER: "app"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
