apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: devops-api
type: Opaque
stringData:
  PGPASSWORD: "changeme"       # Replace with real secret or use external secrets manager
  REDIS_PASSWORD: ""
